/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'VerifySilverTongueSecret': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'UpdateRisk': EventHandler<never, never>
    'StartSilverTongueGame': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { sessionId: string; persona: string; difficulty: number; status: string }>, never>
    'PlayerMessageAPI': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'GetSilverTongueState': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'GameResolution': EventHandler<never, never>
    'AnalyzeIntent': EventHandler<never, { topic: 'intent-inferred'; data: never }>
    'ProcessGreeting': EventHandler<{ timestamp: string; appName: string; greetingPrefix: string; requestId: string }, never>
    'HelloAPI': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { message: string; status: string; appName: string }>, { topic: 'process-greeting'; data: { timestamp: string; appName: string; greetingPrefix: string; requestId: string } }>
  }
    
}