/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'GetHookState': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'StartHookGame': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'HookNextVideo': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'VerifySilverTongueSecret': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'UpdateRisk': EventHandler<never, never>
    'StartSilverTongueGame': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { sessionId: string; persona: string; difficulty: number; status: string }>, never>
    'PlayerMessageAPI': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'GetSilverTongueState': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'GameResolution': EventHandler<never, never>
    'AnalyzeIntent': EventHandler<never, { topic: 'intent-inferred'; data: never }>
    'StartEntangledGame': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'SimulateEntangledChat': EventHandler<never, { topic: 'entangled-chat-simulated'; data: never }>
    'GetEntangledState': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'ResolveEntangledOutcome': EventHandler<never, never>
    'DecideEntangledMatch': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'entangled-decision-made'; data: never }>
  }
    
}